config/routes.rb
Rails.application.routes.draw do
  # verb '/path', to: 'controller#action', as: :prefix
  resources :restaurants do
    resources :reviews, only: [:new, :create]
  end
  resources :reviews, only: [:destroy]
end
# get '/restaurants/top', to: 'restaurants#top', as: :top_restaurants
# get '/restaurants/:id/chef', to: 'restaurants#chef', as: :chef_restaurant
# get '/books', to: 'books#index', as: :books
# get '/games', to: 'games#index', as: :games


# collection -> has to do with ALL restaurants (aka no ID)
# member -> has to do with ONE specific restaurant (aka need ID)
# do
# collection do
#   get :top
# end
# member do
#   get :chef
# end
# end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  # associations
  has_many :reviews # creates a method -> restaurant.reviews
  # has_many :reviews, dependent: :destroy
  # dependent: if we destroy the restaurant, it will also delete all of its reviews
  # validations
  # validates :column_name, actual_validation
  validates :name, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant # creates a method -> review.restaurant
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def top
    @restaurants = Restaurant.where(rating: 1)
  end

  def chef
    @restaurant = Restaurant.find(params[:id])
    # @chef_name = @restaurant.chef_name
  end

  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    # This empty instance is for the form builder
    @restaurant = Restaurant.new
  end

  # this action DOES NOT have a view
  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      # display the form page again
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    # this is for the form builder
    @restaurant = Restaurant.find(params[:id])
  end

  # this action DOES NOT have a view
  def update
    @restaurant = Restaurant.find(params[:id])
    if @restaurant.update(restaurant_params)
      redirect_to restaurant_path(@restaurant)
    else
      # display the form page again
      render :edit, status: :unprocessable_entity
    end
  end

  # this action DOES NOT have a view
  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    # status is for turbo
    redirect_to restaurants_path, status: :see_other
  end

  private

  # strong params -> white listing the info coming from the form
  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :rating)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    # what does the form need? review AND restaurant
    @review = Review.new
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    # i have to give the review the restaurant
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      # if doesnt save, show the 'new' form again
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to restaurant_path(@review.restaurant), status: :see_other
  end

  private

  def review_params
    params.require(:review).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Restaurants1190</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_card.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(http://source.unsplash.com/featured/?<%= restaurant.category.downcase %>&<%= rand(1000) %>)">
  <%= restaurant.name %>
  <%= link_to "", restaurant_path(restaurant), class: "card-link"  %>
</div>

app/views/restaurants/_form.html.erb
<!-- ff + tab -> changed to simple_form_for -->
<%= simple_form_for @restaurant do |f| %>
  <%= f.input :name %>
  <%= f.input :rating %>
  <%= f.submit class: 'btn btn-primary mt-2' %>
<% end %>

app/views/restaurants/_side_info.html.erb
<p class="fw-lighter opacity-75">
  <i class="fas fa-map-pin"></i><span class='ms-2'><%= @restaurant.address %></span>
</p>
<p class="fw-lighter opacity-75">
  <% rand(2..5).times do %>
    <i class="fas fa-dollar-sign"></i>
  <% end %>
</p>
<p class="fw-lighter opacity-75">
  <i class="fas fa-utensils"></i><span class='ms-2'><%= @restaurant.category %></span>
</p>
<p><%#= link_to @restaurant.chef_name, chef_restaurant_path(@restaurant)  %></p>
<div class="d-flex">
  <%= link_to edit_restaurant_path(@restaurant), class: 'text-dark text-decoration-none' do %>
    <i class="fas fa-pencil-alt mx-1"></i>
  <% end %>
  <%= link_to restaurant_path(@restaurant), class: 'text-dark text-decoration-none', data: { turbo_method: :delete, turbo_confirm: "Do you want to delete #{@restaurant.name}" } do %>
    <i class="fas fa-trash mx-1"></i>
  <% end %>
</div>

app/views/restaurants/chef.html.erb
<div class="container">
  <h1><%= @restaurant.chef_name %></h1>
  <p><%= link_to @restaurant.name, restaurant_path(@restaurant)  %></p>
</div>

app/views/restaurants/edit.html.erb
<div class="container">
  <h1>Edit Restaurant</h1>
  <%= render 'restaurants/form' %>
</div>

app/views/restaurants/index.html.erb
<div class="container mt-3">
  <div class="d-flex justify-content-between align-items-center">
    <h1>Restaurants</h1>
    <%= link_to new_restaurant_path, class: 'text-dark text-decoration-none' do %>
      <i class="fa-solid fa-plus"></i>
    <% end %>
  </div>
  <div class="cards">
    <% @restaurants.each do |restaurant| %>
      <%= render 'restaurants/card', restaurant: restaurant %>
    <% end %>
  </div>
</div>

app/views/restaurants/new.html.erb
<div class="container">
  <h1>Add a Restaurant</h1>
  <%= render 'restaurants/form' %>
</div>

app/views/restaurants/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(http://source.unsplash.com/featured/?<%= @restaurant.category.downcase %>&<%= rand(1000) %>/800x333);">
  <div class="container">
  </div>
</div>
<div class="container mt-2">
  <div class="row justify-content-around">
    <div class="col-12 col-sm-8">
      <p>
        <%= link_to '< Restaurants', restaurants_path, class: 'btn-light opacity-25 text-decoration-none' %>
      </p>
      <div class="d-flex align-items-center">
        <h1 class="m-0"><%= @restaurant.name %></h1>
        <p class="m-0 ms-2" style="font-size: 0.8em">
          <% @restaurant.rating.times do %>
            <i class="fas fa-star"></i>
          <% end %>
          <% (5 - @restaurant.rating).times do %>
            <i class="far fa-star"></i>
          <% end %>
        </p>
      </div>
      <p class="fw-lighter opacity-75 mt-2"><%= Faker::Restaurant.description  %></p>
      <h3>Reviews</h3>
      <ul>
        <% @restaurant.reviews.each do |review| %>
          <li><%= review.content %> <%= link_to 'x', review_path(review), data: { turbo_method: :delete, turbo_confirm: 'Delete review?' } %></li>
        <% end %>
      </ul>
      <p><%= link_to 'Add a Review', new_restaurant_review_path(@restaurant), class: 'btn btn-light' %></p>
    </div>
    <div class="col-12 col-sm-4 mt-5">
      <%= render 'restaurants/side_info' %>
    </p>
  </div>
</div>

app/views/restaurants/top.html.erb
<div class="container mt-3">
  <div class="d-flex justify-content-between align-items-center">
    <h1>Top Restaurants</h1>
    <%= link_to new_restaurant_path, class: 'text-dark text-decoration-none' do %>
      <i class="fa-solid fa-plus"></i>
    <% end %>
  </div>
  <div class="cards">
    <% @restaurants.each do |restaurant| %>
      <%= render 'restaurants/card', restaurant: restaurant %>
    <% end %>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="container">
  <h1>Add a Review</h1>
  <!-- The form builds the _path -->
  <%= simple_form_for [@restaurant, @review] do |f| %>
    <%= f.input :content %>
    <%= f.submit class: 'btn btn-success' %>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to restaurants_path, class: "navbar-brand" do %>
      <i class="fas fa-utensils"></i>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <%= link_to "Restaurants", restaurants_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/dmbf29", class: "avatar" %>
        </li>
      </ul>
    </div>
  </div>
</div>